export default {
    gender : 'GENRE',
    homeworld: 'MONDE NATAL',
    height: 'TAILLE',
    mass: 'POIDS',
    species: 'ESPECE',
    masters: 'MAITRES',
    apprentices: 'APPRENTIS',
    wiki: 'En savoir plus sur wiki',
    searchBar: 'Rechercher un personnage',
    home: 'Acceuil',
    characters: 'Personnages',
    favorites: 'Favoris',
    settings: 'Paramètres',
    kilograms: 'kilogrammes',
    meters: 'mètres',
    unknown: 'Inconnue',
    language: 'Change le langage',
    emptyFavorites: 'Favorites Vide',
    darkside: 'Côté obscur'
};