export default {
    gender : 'GENRE',
    homeworld: 'MONDE NATAL',
    height: 'TAILLE',
    mass: 'POIDS',
    species: 'ESPECE',
    masters: 'MAITRES',
    apprentices: 'APPRENTIS',
    wiki: 'En savoir plus sur wiki',
    searchBar: 'Rechercher un personnage',
    home: 'Acceuil',
    characters: 'Personnages',
    favorites: 'Favoris',
    settings: 'Paramètres',
    kilograms: 'kilogrammes',
    meters: 'mètres',
    unknown: 'Inconnue',
    language: 'Change le langage',
    emptyFavorites: 'Favorites Vide',
    darkside: 'Côté obscur',
    hometext: 'Cette application est votre source incontournable pour toutes les informations relatives à l\'univers Star Wars. Que vous soyez un fan inconditionnel ou que vous commenciez tout juste à explorer le monde de Star Wars, notre application contient tout ce que vous devez savoir sur vos personnages préférés, ainsi que leurs détails. De plus, il est possible d\'ajouter vos personnages préférés à vos favoris pour y accéder rapidement. Développée par les programmeurs Bruno Cunha et Noan Randon, Star Native utilise une API Web pour vous apporter les informations les plus récentes sur l\'univers Star Wars. Des informations sur vos personnages préférés à une vue d\'ensemble complète des différents personnages, notre application répond à tous vos besoins.',
    problem: 'Problème avec les données',
};