export const LOAD_FAVORITES_SUCCESS = 'LOAD_FAVORITES_SUCCESS';
export const ADD_FAVORITE_CHARACTER = 'ADD_FAVORITE_CHARACTER';
export const DELETE_FAVORITE_CHARACTER = 'DELETE_FAVORITE_CHARACTER';
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';